### ISSUE TITLE
python version check when installing with pip

### ISSUE THREAD

**Issue by bruggerk** [NBISweden/LocalEGA-cryptor#14]
### Expected Behavior
Have to program run

### Current Behavior
Traceback (most recent call last):
  File "/tmp/lega/venv/bin/lega-cryptor", line 6, in <module>
    from legacryptor.__main__ import main
  File "/tmp/lega/venv/lib/python3.5/site-packages/legacryptor/__main__.py", line 71
    passphrase = getpass(prompt=f'Passphrase for {args["--sk"]}: ')

### Possible Solution
Check that a suitable version of python is being used as the code is using fstrings. It is even possible to install the package with python 2.7, that will suffer from the same issue.

### Steps to Reproduce
Install with a python version < 3.6, and run the program

**Comment by blankdots** [comment]
Python 2 will not be maintained past 2020 ... thus not sure if we should support `2.7` https://pythonclock.org/

Requires an one-liner:
```
assert sys.version_info >= (3, 6), "lega-cryptor requires python3.6"
``` 
before:
https://github.com/NBISweden/LocalEGA-cryptor/blob/master/legacryptor/__main__.py#L132

Maybe worth mentioning a newer version of the GA4GH Crypt4GH format is being developed at: https://github.com/EGA-archive/crypt4gh  which probably can benefit by adding that line too.
